name: benchmark-group-2-multi
on: [pull_request, push]
jobs:
  start-runner:
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-latest
    outputs:
      server-1-label: ${{ steps.start-server-1-ec2-runner.outputs.label }}
      server-1-ec2-instance-id: ${{ steps.start-server-1-ec2-runner.outputs.ec2-instance-id }}
      server-2-label: ${{ steps.start-server-2-ec2-runner.outputs.label }}
      server-2-ec2-instance-id: ${{ steps.start-server-2-ec2-runner.outputs.ec2-instance-id }}
      server-3-label: ${{ steps.start-server-3-ec2-runner.outputs.label }}
      server-3-ec2-instance-id: ${{ steps.start-server-3-ec2-runner.outputs.ec2-instance-id }}
      private-ip-1: ${{ steps.get-private-ip-1.outputs.private-ip }}
      private-ip-2: ${{ steps.get-private-ip-2.outputs.private-ip }}
      private-ip-3: ${{ steps.get-private-ip-3.outputs.private-ip }}
      benchmark-label: ${{ steps.start-benchmark-ec2-runner.outputs.label }}
      benchmark-ec2-instance-id: ${{ steps.start-benchmark-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.GROUP_2_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.GROUP_2_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Start Server 1 EC2 runner
        id: start-server-1-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.GROUP_2_GH_PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-0a1fee7d1926e55ce
          ec2-instance-type: c5.xlarge
          subnet-id: subnet-0f0b102aeba4b75f7
          security-group-id: sg-01dbe69e3eaf89995
      - name: Start Server 2 EC2 runner
        id: start-server-2-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.GROUP_2_GH_PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-0a1fee7d1926e55ce
          ec2-instance-type: c5.xlarge
          subnet-id: subnet-0f0b102aeba4b75f7
          security-group-id: sg-01dbe69e3eaf89995
      - name: Start Server 3 EC2 runner
        id: start-server-3-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.GROUP_2_GH_PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-0a1fee7d1926e55ce
          ec2-instance-type: c5.xlarge
          subnet-id: subnet-0f0b102aeba4b75f7
          security-group-id: sg-01dbe69e3eaf89995
      - name: Start Benchmark EC2 runner
        id: start-benchmark-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.GROUP_2_GH_PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-0a1fee7d1926e55ce
          ec2-instance-type: c5.xlarge
          subnet-id: subnet-0f0b102aeba4b75f7
          security-group-id: sg-01dbe69e3eaf89995
      - name: Get private IP address 1
        id: get-private-ip-1
        run: | 
          echo "private-ip=$(aws ec2 describe-instances \
           --instance-id ${{ steps.start-server-1-ec2-runner.outputs.ec2-instance-id }} \
           --query 'Reservations[0].Instances[0].PrivateIpAddress' | tr -d '"')" \
           >> $GITHUB_OUTPUT
      - name: Get private IP address 2
        id: get-private-ip-2
        run: | 
          echo "private-ip=$(aws ec2 describe-instances \
           --instance-id ${{ steps.start-server-2-ec2-runner.outputs.ec2-instance-id }} \
           --query 'Reservations[0].Instances[0].PrivateIpAddress' | tr -d '"')" \
           >> $GITHUB_OUTPUT
      - name: Get private IP address 3
        id: get-private-ip-3
        run: | 
          echo "private-ip=$(aws ec2 describe-instances \
           --instance-id ${{ steps.start-server-3-ec2-runner.outputs.ec2-instance-id }} \
           --query 'Reservations[0].Instances[0].PrivateIpAddress' | tr -d '"')" \
           >> $GITHUB_OUTPUT
  run-server-1:
    name: Start the ISTZIIO server 1
    needs: start-runner # required to start the main job when the runner is ready
    runs-on: ${{ needs.start-runner.outputs.server-1-label }} # run the job on the newly created runner  
    env:
      SERVER_ROOT: ${{ github.workspace }}/server
      AWS_ACCESS_KEY_ID: ${{ secrets.GROUP_2_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.GROUP_2_AWS_SECRET_ACCESS_KEY }}
      SERVER_IP: ${{ needs.start-runner.outputs.private-ip-1 }}
      NODE_1_IP: ${{ needs.start-runner.outputs.private-ip-1 }}
      NODE_2_IP: ${{ needs.start-runner.outputs.private-ip-2 }}
      NODE_3_IP: ${{ needs.start-runner.outputs.private-ip-3 }}
    steps:
      - name: Clone Server
        uses: actions/checkout@v4
        with:
          repository: cmu-db/15721-s24-cache2
          ref: benchmark
      - name: Build Server
        run: |
          cargo build --bin istziio_server_node
      - name: start server nodes
        run: ${{ github.workspace }}/server/run_single_node.sh
      - name: wait for server completing setups
        run: |
          sleep 5
          cat ${{ github.workspace }}/logs/app_6379.log
      - name: spin
        run: sleep 60
  run-server-2:
    name: Start the ISTZIIO server 2
    needs: start-runner # required to start the main job when the runner is ready
    runs-on: ${{ needs.start-runner.outputs.server-2-label }} # run the job on the newly created runner  
    env:
      SERVER_ROOT: ${{ github.workspace }}/server
      AWS_ACCESS_KEY_ID: ${{ secrets.GROUP_2_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.GROUP_2_AWS_SECRET_ACCESS_KEY }}
      SERVER_IP: ${{ needs.start-runner.outputs.private-ip-2 }}
      NODE_1_IP: ${{ needs.start-runner.outputs.private-ip-1 }}
      NODE_2_IP: ${{ needs.start-runner.outputs.private-ip-2 }}
      NODE_3_IP: ${{ needs.start-runner.outputs.private-ip-3 }}
    steps:
      - name: Clone Server
        uses: actions/checkout@v4
        with:
          repository: cmu-db/15721-s24-cache2
          ref: benchmark
      - name: Build Server
        run: |
          cargo build --bin istziio_server_node
      - name: start server nodes
        run: ${{ github.workspace }}/server/run_single_node.sh
      - name: wait for server completing setups
        run: |
          sleep 5
          cat ${{ github.workspace }}/logs/app_6379.log
      - name: spin
        run: sleep 60
  run-server-3:
    name: Start the ISTZIIO server 3
    needs: start-runner # required to start the main job when the runner is ready
    runs-on: ${{ needs.start-runner.outputs.server-3-label }} # run the job on the newly created runner  
    env:
      SERVER_ROOT: ${{ github.workspace }}/server
      AWS_ACCESS_KEY_ID: ${{ secrets.GROUP_2_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.GROUP_2_AWS_SECRET_ACCESS_KEY }}
      SERVER_IP: ${{ needs.start-runner.outputs.private-ip-3 }}
      NODE_1_IP: ${{ needs.start-runner.outputs.private-ip-1 }}
      NODE_2_IP: ${{ needs.start-runner.outputs.private-ip-2 }}
      NODE_3_IP: ${{ needs.start-runner.outputs.private-ip-3 }}
    steps:
      - name: Clone Server
        uses: actions/checkout@v4
        with:
          repository: cmu-db/15721-s24-cache2
          ref: benchmark
      - name: Build Server
        run: |
          cargo build --bin istziio_server_node
      - name: start server nodes
        run: ${{ github.workspace }}/server/run_single_node.sh -c
      - name: wait for server completing setups
        run: |
          sleep 5
          cat ${{ github.workspace }}/logs/app_6379.log
      - name: spin
        run: sleep 60
  run-benchmark:
    name: Run Benchmark
    needs: 
      - start-runner
    runs-on: ${{ needs.start-runner.outputs.benchmark-label }} # run the job on the newly created runner  
    env:
      SERVER_URL: http://${{ needs.start-runner.outputs.private-ip-1 }}:26379
    steps:
      - name: Clone Server
        uses: actions/checkout@v4
      - name: Build Benchmark driver
        run: cargo build
      - name: Wait for server
        run: |
          until curl --output /dev/null --silent --head --fail $SERVER_URL/; do
              printf '.'
              sleep 5
          done
      - name: Run Benchmark
        run: cargo run
  stop-runner:
    name: Stop self-hosted EC2 runner
    needs:
      - start-runner # required to get output from the start-runner job
      - run-server-1 
      - run-server-2 
      - run-server-3 
      - run-benchmark
    runs-on: ubuntu-latest
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.GROUP_2_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.GROUP_2_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Stop Server 1 EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.GROUP_2_GH_PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner.outputs.server-1-label }}
          ec2-instance-id: ${{ needs.start-runner.outputs.server-1-ec2-instance-id }}
      - name: Stop Server 2 EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.GROUP_2_GH_PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner.outputs.server-2-label }}
          ec2-instance-id: ${{ needs.start-runner.outputs.server-2-ec2-instance-id }}
      - name: Stop Server 3 EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.GROUP_2_GH_PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner.outputs.server-3-label }}
          ec2-instance-id: ${{ needs.start-runner.outputs.server-3-ec2-instance-id }}
      - name: Stop Benchmark EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.GROUP_2_GH_PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner.outputs.benchmark-label }}
          ec2-instance-id: ${{ needs.start-runner.outputs.benchmark-ec2-instance-id }}
          